# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20170829_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantlocation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='restaurantlocation',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='restaurantlocation',
            name='updated',
        ),
    ]
